services:
  - type: web
    name: expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

databases:
  - name: expense-tracker-db
    plan: free